/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basic;

import serialization.PersistantTime;
import generics.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // PersistantTime time = new PersistantTime();
        Generics2 ag = new Generics2();
        
    }

}
